# SPDX-License-Identifier: AGPL-3.0-only
import copy
from pathlib import Path
import sys
import unittest

sys.path.insert(0,str(Path(__file__).resolve().parents[1]/"tools"))
import check_z_slicing as check
from check_slicing import parse


def fixture(percent=0, geometry=None):
    """Synthetic Z-B slice planes, rounded to the common fixed layer grid."""
    geometry = percent if geometry is None else geometry
    factor = 100/(100-geometry)
    tops = [round((n*factor-.2)/.15)*.15+.2 for n in (40,80,120)]
    layers = [round(.2+i*.15,5) for i in range(round((tops[-1]-.2)/.15)+1)]
    def face(coordinate):
        return dict(coordinate_mm=coordinate,width_mm=.45,line=1)
    return dict(config={check.XY_KEY:"0%",check.Z_KEY:f"{percent}%", "xy_size_compensation":"0", "layer_height":"0.15"},
                layer_z_mm=layers,
                faces={.65:{"X":[face(99.225),face(150.775)],"Y":[face(93.225),face(116.775)]}},
                external_segments=[dict(z_mm=z,start=[x-5,110],end=[x+5,110],width_mm=.45,line=i+1)
                                   for i,(x,z) in enumerate(zip((111,125,139),tops))])


class ZSlicingTests(unittest.TestCase):
    def test_three_step_levels_move_on_the_same_layer_grid(self):
        report = check.compare(fixture(),fixture(.5),.5)
        self.assertEqual(report["status"],"Z_TRAJECTORY_SCALE_CONFIRMED")
        self.assertEqual(report["baseline_layer_count"],800)
        self.assertEqual(report["compensated_layer_count"],804)
        self.assertAlmostEqual(report["steps"][0]["observed_delta_mm"],.3)
        self.assertAlmostEqual(report["steps"][1]["observed_delta_mm"],.45)
        self.assertAlmostEqual(report["steps"][2]["observed_delta_mm"],.6)
        self.assertEqual(report["physical_validation"],"NOT_ESTABLISHED")

    def test_percentage_only_change_and_wrong_scale_are_rejected(self):
        for geometry in (0,1.5):
            with self.subTest(geometry=geometry),self.assertRaisesRegex(ValueError,"Z trajectory mismatch"):
                check.compare(fixture(),fixture(.5,geometry),.5)

    def test_xy_change_variable_layers_and_missing_blade_are_rejected(self):
        for mutate in (lambda p:p["config"].update(filament_shrinkage_compensation_xy=".5%"),
                       lambda p:p["layer_z_mm"].__setitem__(2,.51),
                       lambda p:p["external_segments"].pop(0),
                       lambda p:p["faces"][.65]["X"][0].update(coordinate_mm=90)):
            p=copy.deepcopy(fixture(.5));mutate(p)
            with self.assertRaises(ValueError):
                check.compare(fixture(),p,.5)

    def test_segment_recording_uses_positive_extrusion_and_actual_z(self):
        text="""; generated by PrusaSlicer SYNTHETIC
G90
M83
G1 X0 Y0 Z1
;Z:1
;TYPE:External perimeter
;WIDTH:0.45
G1 X10 E1
G1 Y5 E-1
G1 X0
G1 Y0 E1
; prusaslicer_config = begin
; layer_height = .15
; prusaslicer_config = end
"""
        result=parse(text,record_segments=True)
        self.assertEqual(len(result["external_segments"]),2)
        self.assertEqual(result["external_segments"][1]["start"],[0,5])
        self.assertNotIn("external_segments",parse(text))
        with self.assertRaisesRegex(ValueError,"extrusion Z"):
            parse(text.replace("Z1","Z2"),record_segments=True)


if __name__ == "__main__":
    unittest.main()
