# SPDX-License-Identifier: AGPL-3.0-only
import copy
from pathlib import Path
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
import check_slicing as check


def gcode(percent=0, geometry_percent=None, relative=True):
    """Small synthetic flat-face path; never represented as an actual export."""
    geometry_percent = percent if geometry_percent is None else geometry_percent
    extent = 145*100/(100-geometry_percent)-.45
    lines = ["; generated by PrusaSlicer SYNTHETIC", "G90", "M83" if relative else "M82"]
    for z in (.65, .8, .95):
        lines += [f";Z:{z}", "G92 E0", f"G1 X0 Y0 Z{z}", ";TYPE:External perimeter", ";WIDTH:0.45",
                  f"G1 X{extent:.3f} E1", f"G1 Y{extent:.3f} E{1 if relative else 2}",
                  f"G1 X0 E{1 if relative else 3}", f"G1 Y0 E{1 if relative else 4}",
                  # Retraction and travel, still under the external role, must
                  # not enlarge the span. Then an extruding skirt is ignored.
                  f"G1 X500 E{-1 if relative else 3}", "G1 X600 Y600", ";TYPE:Skirt/Brim",
                  f"G1 X650 Y650 E{2 if relative else 5}"]
    lines += ["; prusaslicer_config = begin", f"; {check.XY_KEY} = {percent}%",
              f"; {check.Z_KEY} = 0%", "; xy_size_compensation = 0", "; prusaslicer_config = end"]
    return "\n".join(lines)


class SlicingTests(unittest.TestCase):
    def test_recorded_ubuntu_apply_is_required_and_tampering_is_detected(self):
        path = Path(__file__).resolve().parents[1] / "research/evidence/xy-s-software/SYNTHETIC-apply-result.json"
        record = check.strict_json(path.read_text())
        self.assertAlmostEqual(check.applied_percent(record), .5)
        for mutate in (lambda r: r.update(apply_status="UNCONFIRMED"),
                       lambda r: r["artifacts"]["xy"].update(id="DA-XY-A"),
                       lambda r: r["proposed_settings"][0]["before"].update(numeric=.1),
                       lambda r: r["plan"]["xy"].update(shrinkage_percent=.3)):
            changed = copy.deepcopy(record)
            mutate(changed)
            with self.assertRaises(ValueError):
                check.applied_percent(changed)

    def test_actual_motion_not_comments_determines_the_result(self):
        baseline = check.parse(gcode())
        report = check.compare(baseline, check.parse(gcode(.5)), .5)
        self.assertEqual(report["status"], "TRAJECTORY_SCALE_CONFIRMED")
        self.assertEqual(report["checked_layer_count"], 3)
        self.assertEqual(report["physical_validation"], "NOT_ESTABLISHED")
        # A changed setting footer on an unchanged trajectory must fail.
        with self.assertRaisesRegex(ValueError, "trajectory scale mismatch"):
            check.compare(baseline, check.parse(gcode(.5, geometry_percent=0)), .5)

    def test_wrong_scale_formula_and_direction_fail(self):
        baseline = check.parse(gcode())
        for geometry in (-.5, 1):
            with self.subTest(geometry=geometry), self.assertRaisesRegex(ValueError, "trajectory"):
                check.compare(baseline, check.parse(gcode(.5, geometry)), .5)

    def test_absolute_and_relative_extrusion_agree(self):
        for percent in (0, .5, -.5):
            a, b = check.parse(gcode(percent, relative=True)), check.parse(gcode(percent, relative=False))
            for axis in "XY":
                self.assertEqual(check.envelope(a, .65, axis), check.envelope(b, .65, axis))
        report = check.compare(check.parse(gcode()), check.parse(gcode(-.5)), -.5)
        self.assertLess(report["expected_span_delta_mm"], 0)

    def test_changed_profile_or_z_cannot_pass_as_xy_only(self):
        baseline, compensated = check.parse(gcode()), check.parse(gcode(.5))
        for mutation in (lambda p: p["config"].update(xy_size_compensation=".1"),
                         lambda p: p["config"].update(layer_height=".2"),
                         lambda p: p["layer_z_mm"].append(1.1)):
            changed = copy.deepcopy(compensated)
            mutation(changed)
            with self.assertRaises(ValueError):
                check.compare(baseline, changed, .5)

    def test_missing_tags_modes_and_duplicate_config_fail_closed(self):
        variants = (gcode().replace(";WIDTH:0.45", ""), gcode().replace("G90", "G20"),
                    gcode().replace("G90", "G91"), gcode().replace("G92 E0", "G92 X0"),
                    gcode()+"\n; prusaslicer_config = begin",
                    gcode().replace("; xy_size_compensation = 0", "; xy_size_compensation = 0\n; xy_size_compensation = 1"))
        for variant in variants:
            with self.subTest(variant=variant[:70]), self.assertRaises(ValueError):
                check.parse(variant)

    def test_arcs_advance_position_but_are_not_flat_contact_faces(self):
        source = gcode().replace("G1 X144.550 E1", "G2 X144.550 Y1 I72 J0 E1")
        parsed = check.parse(source)
        self.assertEqual(check.envelope(parsed, .65, "X")["high"]["coordinate_mm"], 144.55)


if __name__ == "__main__":
    unittest.main()
