#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Check XY-S flat outer-face trajectories in two actual PrusaSlicer ASCII G-codes.

This is a bounded single-object, axis-aligned XY-only software check, not a
general G-code simulator or a prediction of deposited/printed dimensions.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import re

from result import strict_json, validate_record

XY_KEY = "filament_shrinkage_compensation_xy"
Z_KEY = "filament_shrinkage_compensation_z"
NUMBER = r"[+-]?(?:\d+(?:\.\d*)?|\.\d+)"


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def parse(text):
    if not text.startswith("; generated by PrusaSlicer"):
        raise ValueError("expected PrusaSlicer ASCII G-code")
    # Only the authoritative legacy config footer is read; thumbnails and
    # arbitrary comments with the same words do not count as settings.
    config, in_config, config_count = {}, False, 0
    position = dict(X=None, Y=None, Z=None, E=0.)
    relative_e = False
    role, width, layer = None, None, None
    layers, faces = [], {}
    for line_number, line in enumerate(text.splitlines(), 1):
        if line == "; prusaslicer_config = begin":
            in_config = True
            config_count += 1
            continue
        if line == "; prusaslicer_config = end":
            in_config = False
            continue
        if in_config:
            match = re.fullmatch(r"; (\w+) = (.*)", line)
            if match:
                key, value = match.groups()
                if key in config:
                    raise ValueError("duplicate config key: " + key)
                config[key] = value
            continue
        if line.startswith(";TYPE:"):
            role = line[6:]
        elif line.startswith(";WIDTH:"):
            width = float(line[7:])
            if not math.isfinite(width) or width <= 0:
                raise ValueError("invalid extrusion width")
        elif line.startswith(";Z:"):
            layer = float(line[3:])
            if not math.isfinite(layer):
                raise ValueError("invalid layer height")
            layers.append(layer)
        code = line.split(";", 1)[0].strip()
        if not code:
            continue
        command = code.split()[0]
        if command in ("G20", "G91", "G90.1", "G91.1"):
            raise ValueError("unsupported units/coordinate mode: " + command)
        if command == "G90":
            # Marlin G90 resets the extrusion mode; M83 can override it.
            relative_e = False
        elif command == "M82":
            relative_e = False
        elif command == "M83":
            relative_e = True
        elif command.startswith("T") and command != "T0":
            raise ValueError("only extruder 0 is supported")
        elif command in ("G0", "G1", "G2", "G3", "G92"):
            fields = dict((key, float(value)) for key, value in re.findall(r"([XYZE])("+NUMBER+r")", code))
            if any(not math.isfinite(v) for v in fields.values()):
                raise ValueError("nonfinite G-code coordinate")
            if command == "G92":
                if any(k != "E" for k in fields):
                    raise ValueError("G92 coordinate shifts are outside this check")
                position.update(fields)
                continue
            start = position.copy()
            for key, value in fields.items():
                position[key] = position[key] + value if key == "E" and relative_e else value
            extrusion = position["E"] - start["E"]
            # Arcs update the cursor but are deliberately not used as contact
            # planes. The gauge has long straight outer faces on all four ends.
            if (command == "G1" and extrusion > 0 and role == "External perimeter" and layer is not None
                    and all(start[k] is not None and position[k] is not None for k in "XYZ")):
                if abs(start["Z"] - layer) > 1e-5 or abs(position["Z"] - layer) > 1e-5:
                    raise ValueError("extrusion Z disagrees with the layer tag")
                for axis, along in (("X", "Y"), ("Y", "X")):
                    if abs(position[axis]-start[axis]) < 1e-8 and abs(position[along]-start[along]) >= 5:
                        if width is None:
                            raise ValueError("missing width for an external contact face")
                        faces.setdefault(layer, {}).setdefault(axis, []).append(dict(
                            coordinate_mm=position[axis], width_mm=width, line=line_number))
    if config_count != 1 or in_config or not config or not layers:
        raise ValueError("missing or incomplete G-code config/layer metadata")
    return dict(config=config, layer_z_mm=layers, faces=faces, generator=text.splitlines()[0])


def numeric_setting(config, key, percent=False):
    value = config.get(key, "")
    if percent:
        if not value.endswith("%"):
            raise ValueError("missing single-material percentage: " + key)
        value = value[:-1]
    if not re.fullmatch(NUMBER, value):
        raise ValueError("missing or non-scalar setting: " + key)
    value = float(value)
    if not math.isfinite(value):
        raise ValueError("invalid setting: " + key)
    return value


def envelope(parsed, z, axis):
    values = parsed["faces"].get(z, {}).get(axis, [])
    if len(values) < 2:
        raise ValueError(f"missing flat {axis} contact faces at Z={z}")
    low = min(values, key=lambda v: v["coordinate_mm"])
    high = max(values, key=lambda v: v["coordinate_mm"])
    # An Arachne path may vary its width elsewhere. Only the two measured end
    # faces are used, and every fragment at either extreme must agree in width.
    for face in (low, high):
        if any(abs(v["width_mm"]-face["width_mm"]) > 1e-5 for v in values
               if abs(v["coordinate_mm"]-face["coordinate_mm"]) < 1e-8):
            raise ValueError("varying width at an outer contact face")
    centerline = high["coordinate_mm"] - low["coordinate_mm"]
    return dict(low=low, high=high, centerline_span_mm=centerline,
                nominal_boundary_span_mm=centerline+(low["width_mm"]+high["width_mm"])/2)


def compare(before, after, percent, tolerance_mm=.005):
    if not math.isfinite(percent) or not -10 <= percent <= 10 or abs(percent) < .01:
        raise ValueError("use a nonzero test shrinkage between -10 and 10 percent, magnitude >= .01")
    if not math.isfinite(tolerance_mm) or not 0 < tolerance_mm <= .02:
        raise ValueError("trajectory tolerance must be > 0 and <= .02 mm")
    for parsed, expected in ((before, 0), (after, percent)):
        if abs(numeric_setting(parsed["config"], XY_KEY, True)-expected) > 1e-6:
            raise ValueError("G-code XY shrinkage differs from the expected setting")
        if numeric_setting(parsed["config"], Z_KEY, True) != 0 or numeric_setting(parsed["config"], "xy_size_compensation") != 0:
            raise ValueError("other compensation must remain zero")
    differences = sorted(k for k in before["config"].keys() | after["config"].keys()
                         if before["config"].get(k) != after["config"].get(k))
    if differences != [XY_KEY]:
        raise ValueError("unexpected G-code configuration changes: " + ", ".join(differences))
    if before["layer_z_mm"] != after["layer_z_mm"]:
        raise ValueError("XY-only apply changed the layer schedule")
    z_values = [z for z in before["layer_z_mm"] if .6 <= z <= 3.0]
    if len(z_values) < 3 or len(z_values) != len(set(z_values)):
        raise ValueError("need at least three distinct middle layers of a single XY-S object")
    factor = 100/(100-percent)
    expected_delta = 145*(factor-1)
    rows = []
    for z in z_values:
        for axis in "XY":
            b, a = envelope(before, z, axis), envelope(after, z, axis)
            for face in ("low", "high"):
                if abs(a[face]["width_mm"]-b[face]["width_mm"]) > 1e-5:
                    raise ValueError("extrusion width changed at the measured contact face")
            delta = a["centerline_span_mm"] - b["centerline_span_mm"]
            if (abs(b["nominal_boundary_span_mm"]-145) > tolerance_mm or
                    abs(a["nominal_boundary_span_mm"]-145*factor) > tolerance_mm or
                    abs(delta-expected_delta) > tolerance_mm):
                raise ValueError(f"trajectory scale mismatch at Z={z} {axis}: observed delta {delta:.6f}, expected {expected_delta:.6f} mm")
            rows.append(dict(z_mm=z, axis=axis, baseline=b, compensated=a,
                             measured_delta_mm=delta, delta_error_mm=delta-expected_delta))
    return dict(status="TRAJECTORY_SCALE_CONFIRMED", physical_validation="NOT_ESTABLISHED",
                artifact_id="DA-XY-S", artifact_revision=1, nominal_span_mm=145,
                baseline_xy_percent=0, compensated_xy_percent=percent, expected_scale_factor=factor,
                expected_span_delta_mm=expected_delta, tolerance_mm=tolerance_mm,
                checked_layer_count=len(z_values), unchanged_layer_z_mm=before["layer_z_mm"],
                changed_config_keys=differences, measurements=rows)


def applied_percent(record):
    validate_record(record)
    if (record.get("solver_version") != "3.0.0" or
            record.get("artifacts", {}).get("xy") != {"id": "DA-XY-S", "revision": 1}):
        raise ValueError("requires a solver 3.0.0 XY-S revision 1 result")
    if record["apply_status"] != "CONFIRMED" or record["readback_status"] != "MATCHED":
        raise ValueError("requires an actual confirmed plugin apply/readback record")
    writes = [p for p in record["proposed_settings"] if p.get("write_requested")]
    if len(writes) != 1 or writes[0]["key"] != XY_KEY or writes[0]["owner"] != "filament_slot_1":
        raise ValueError("requires an XY-only apply to slot 1")
    if writes[0]["before"].get("numeric") != 0 or not writes[0]["before"].get("known"):
        raise ValueError("plugin must have observed zero before applying")
    percent = record["plan"]["xy"]["shrinkage_percent"]
    if abs(percent-writes[0]["proposed"]) > 1e-6:
        raise ValueError("proposal disagrees with the calculated plan")
    return percent


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("baseline", type=Path)
    parser.add_argument("compensated", type=Path)
    parser.add_argument("--apply-result", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        record = strict_json(args.apply_result.read_text())
        report = compare(parse(args.baseline.read_text()), parse(args.compensated.read_text()), applied_percent(record))
        report["sha256"] = {key:sha256(path) for key, path in
                            (("baseline_gcode", args.baseline), ("compensated_gcode", args.compensated), ("apply_result", args.apply_result))}
        with args.output.open("x") as stream:
            json.dump(report, stream, indent=2, allow_nan=False)
            stream.write("\n")
        print(f"{report['status']}: {report['checked_layer_count']} layers × X/Y; physical validation NOT_ESTABLISHED")
    except (ValueError, OSError, KeyError) as error:
        parser.exit(1, f"ERROR: {error}\n")


if __name__ == "__main__":
    main()
